language: python

cache: pip

python:
  - "3.5"

os: linux

dist: trusty

sudo: required

before_install:
  # Setup conda (needed for opencv, ray dependency)
  # WARNING: enforces py3.6
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - export TEST_FLAG="True"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda install python=3.5.2
  - python -V

  # Set up requirements for flow
  - conda env create -f environment.yml
  - source activate flow

  # Requirements for Ray
  - pip install opencv-python
  # Setup ray from https://s3-us-west-2.amazonaws.com/ray-wheels/
  - pip install https://s3-us-west-1.amazonaws.com/flow.utils/ray-0.5.3-cp35-cp35m-manylinux1_x86_64.whl
  - pip install redis~=2.10.6

  # Copy over local rllib changes (testing branch)
  - pushd $HOME/build/flow-project
  -     git clone https://github.com/flow-project/ray.git
  -     cd ray && git fetch && git checkout ray_merge && cd ..
  -     pushd ray
  -         RAY_SITE_DIR=`python -c "import ray; print(ray.__path__[0])"`
  -         rm -rf $RAY_SITE_DIR/rllib
  -         ls $RAY_SITE_DIR
  -         cp -r python/ray/rllib $RAY_SITE_DIR/rllib
  -     popd
  - popd

  # [sumo] dependencies and binaries
  - pushd $HOME/build/flow-project
  -     ./flow/scripts/setup_sumo_ubuntu1404.sh
  - popd
  - source ~/.bashrc

  - ls ../

install:
  - pip install flake8 .
  - pip install coveralls
  - pip install nose
  - pip install matplotlib
  - pip install jupyter

before_script:
  - flake8 --version
  - flake8 --show-source

script:
  - python setup.py install
  - nose2 --with-coverage

after_success:
  - coveralls
